// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvtojojfwkryzixshczr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2dG9qb2pmd2tyeXppeHNoY3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzMxNjcsImV4cCI6MjA3MzA0OTE2N30.8eQ8YMRn2uYfF_PprMeRoIBDxpGaiCjvyWHKmmuepco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});